### ISSUE TITLE
第一章 4.3节 一个补充

### ISSUE THREAD

**Issue by xqzp486** [Francis-xsc/atguigu_shk_mysql_pdf#2]
第一章 4.3节 有个密码强度评估函数
`VALIDATE_PASSWORD_STRENGTH`

| Password Test                             | Return Value |
| ----------------------------------------- | ------------ |
| Length < 4                                | 0            |
| Length ≥ 4 and < validate_password.length | 25           |
| Satisfies policy 1 (LOW)                  | 50           |
| Satisfies policy 2 (MEDIUM)               | 75           |
| Satisfies policy 3 (STRONG)               | 100          |

当密码强度符合MEDIUM时，返回值是75。这个需要补充一个前提
就是必须有字典文件，才可能会有75这个返回值，
没有字典文件的时候，密码强度符合MEDIUM时，返回值是100

MEDIUM 验证长度 数字 大小写 特殊字符
STRONG 验证长度 数字 大小写 特殊字符 字典文件

什么是字典文件，可以理解成一个文本，上面有一行一行的单词

假如 密码长度 数字 大小写 特殊字符，都满足要求
但是包含了字典文件中的单词，那么返回值就是75
如果没有包含字段字典文件中的单词，那么返回值就是100

**Comment by Francis-xsc** [comment]
已修改
